#!/usr/bin/python3
import smtplib
import argparse
import email

from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

parser = argparse.ArgumentParser()
parser.add_argument("Objetivo", help="Objetivo da mensagem enviada. | R para redefinição de senha.| F para refefinição de senha falha | C para cadastro. | ")
parser.add_argument("From", help="Email remetente")
parser.add_argument("Password", help="Senha de login do email remetente")
parser.add_argument("To", help="Email destinatário")
parser.add_argument("Name", help="nome do novo moderador (será inserido no corpo do email)")
parser.add_argument("Username", help="nome de usuário do novo moderador (será inserido no corpo do email)")
parser.add_argument("newPassword", help="senha do novo moderador (será inserido no corpo do email)")
args = parser.parse_args()


if args.Objetivo == "C":
    server = smtplib.SMTP('smtp.gmail.com:587')

    msg = MIMEMultipart("alternative")
    msg.set_charset("utf-8")

    email_content = MIMEText(f"""
    <html>

    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
     <style>div.wrapper {{
  display:flex;
  flex-direction:column;
  justify-content:center;
  align-content:center;
  background-color:#121212;
  color:white;
  text-align:center;
  margin:auto; 
}}

.title {{
  color:#1DA1F2;
}}</style>
    </head>

    <body>
    <div clas="wrapper">
    <h1 class="title">Cadastrado</h1> 
    <p>Nome: {args.Name}</p>
    <p>Nome de Usuário:{args.Username}</p>
    <p>Nome de Usuário:{args.newPassword}</p> 
    </div>
    <a href="http://localhost:/TCC/home">Catálogo de Curso</a>
    </body>
    </html>


    """, 'html')

    msg['Subject'] = 'Conta cadastrada com sucesso!'

    msg['From'] = args.From
    msg['To'] = args.To
    password = "covid-19"

    msg.add_header('Content-Type', 'text/html')
    msg.attach(email_content)

    s = smtplib.SMTP('smtp.gmail.com: 587')
    s.starttls()

    # Login Credentials for sending the mail
    s.login(msg['From'], password)

    s.sendmail(msg['From'], [msg['To']], msg.as_string())

elif args.Objetivo == "R":
    server = smtplib.SMTP('smtp.gmail.com:587')

    msg = MIMEMultipart("alternative")
    msg.set_charset("utf-8")

    email_content = MIMEText(f"""
 <html>

    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
      
      <style>div.wrapper {{
  display:flex;
  flex-direction:column;
  justify-content:center;
  align-content:center;
  background-color:#121212;
  color:white;
  text-align:center;
  margin:auto; 
}}

.title {{
  color:#1DA1F2;
}}</style>
    </head>

    <body>
    <div class="wrapper">
      <h1 class="title">Catálogo de Cursos</h1>
    <h1>Nova senha:</h1> 
    <p>{args.newPassword}</p>
    </div>
       <a href="http://localhost:/TCC/home">Catálogo de Curso</a>
    </body>
    </html>



    """, 'html')

    msg['Subject'] = 'Redefinição de Senha'

    msg['From'] = args.From
    msg['To'] = args.To
    password = "covid-19"

    msg.add_header('Content-Type', 'text/html')
    msg.attach(email_content)

    s = smtplib.SMTP('smtp.gmail.com: 587')
    s.starttls()

    # Login Credentials for sending the mail
    s.login(msg['From'], password)

    s.sendmail(msg['From'], [msg['To']], msg.as_string())

elif args.Objetivo == "F":
    server = smtplib.SMTP('smtp.gmail.com:587')

    msg = MIMEMultipart("alternative")
    msg.set_charset("utf-8")

    email_content = MIMEText(f"""
    <html>

    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
      
      <style>div.wrapper {{
  display:flex;
  flex-direction:column;
  justify-content:center;
  align-content:center;
  background-color:#121212;
  color:white;
  text-align:center;
  margin:auto; 
}}

.title {{
  color:#1DA1F2;
}}</style>
    </head>

    <body>
    <div class="wrapper">
      <h1 class="title">Catálogo de Cursos</h1>
    <h1>Conta não Cadastrada</h1>
    <p>Este email não possui conta no sistema, faça cadastro ou peça ao administrador.</p> <br>
      
    </div>
      <a href="http://localhost:/TCC/home">Catálogo de Curso</a>
      <p></p>
    </body>
    </html>

    """, 'html')

    msg['Subject'] = 'Redefinição de Senha'

    msg['From'] = args.From
    msg['To'] = args.To
    password = "covid-19"

    msg.add_header('Content-Type', 'text/html')
    msg.attach(email_content)

    s = smtplib.SMTP('smtp.gmail.com: 587')
    s.starttls()

    # Login Credentials for sending the mail
    s.login(msg['From'], password)

    s.sendmail(msg['From'], [msg['To']], msg.as_string())








